spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: C0dingS@int
  cloud:
    config:
      override-system-properties: false    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8083

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
